import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <div className="bg-slate-300 w-full h- text-black flex items-center justify-around text-2xl">
        <h1>serch</h1>
        <h1>antaka</h1>
        <h1>filter</h1>
      </div>
      <div className='bg-white text-black ' >
      {children}
      </div>
        </body>
    </html>
  )
}
